### ISSUE TITLE
Still getting errors?

### ISSUE THREAD

**Issue by diogoprov** [msperlin/GetLattesData#10]
Hi Marcelo,
it seems that Lattes is back again without captcha, but I'm still getting an error when running the example script.

After downloading the data from the IDs, I got this: 

```
Error: XML content does not seem to be XML: '/var/folders/kd/_k75gv855qxbyrqq0rtqk1w40000gr/T//Rtmpy6VvBp/curriculo.xml'
In addition: Warning message:
In utils::unzip(zip.in, exdir = my.tempdir) :
  error 1 in extracting from zip file
```

Is this the same error of the time with captcha or I'm doing something wrong?

**Comment by msperlin** [comment]
The issue is that, for the xml zipped files, the captcha is still on. 

You can still download the zip files mannualy and latter reade with gld_read_zip.

**Comment by msperlin** [comment]
I should soon release a new version of Getlattesdata, but it will probably come with less features.

**Comment by diogoprov** [comment]
No problem, thanks a lot Marcelo! I'll try to download them manually

**Comment by msperlin** [comment]
Hi, 

I just posted a new version of the package on github and CRAN. Now one must use local zip files to read the data. 

Best,

**Comment by diogoprov** [comment]
Oi Perlin,
teria um vignette novo pra fazer o que vc exemplifica mas com essa função nova que lê os zips?

Obrigado

**Comment by diogoprov** [comment]
Baixei todos os 28 cv que me interessavam em .xml e fiz um .zip deles. Estou anexando ele aqui:

[Arquivo Comprimido.zip](https://github.com/msperlin/GetLattesData/files/2470534/Arquivo.Comprimido.zip)

Rodei as seguintes linhas: 

```
f.in <- system.file("Arquivo Comprimido.zip", package = 'GetLattesData')
my.l <- gld_read_zip(f.in)
Error in gld_read_zip(f.in) : File does not exists..
```

```
f.in <- system.file("Arquivo Comprimido.zip", package = 'GetLattesData')
l.out <- gld_get_lattes_data_from_zip(f.in, field.qualis = field.qualis)
Error in gld_get_lattes_data_from_zip(f.in, field.qualis = field.qualis) : 
  All files in zip.files input should be with .zip extension. Check your inputs..
```

Tive esses erros. Mas se faço isso: 

```
my.l <- gld_read_zip("Arquivo Comprimido.zip")
l.out <- gld_get_lattes_data_from_zip("Arquivo Comprimido.zip", field.qualis = field.qualis)
```

Consigo ler normalmente. O ponto é que ele só lê o 1o curriculo, e todas as análises ficam sendo e uma só pessoa. O que estou fazendo errado?

**Comment by msperlin** [comment]
Oi Diogo, 

O formato esperado é um curriculo por arquivo e não um com todos.

Veja exemplo aqui:

https://msperlin.github.io/2018-10-11-Update-GetLattesData/

**Comment by smolski** [comment]
Olá!
O atalho https://msperlin.github.io/2018-10-11-Update-GetLattesData/ não está ativo, teria outro?

Cordialmente

**Comment by msperlin** [comment]
Sim:

https://www.msperlin.com/blog/post/2018-10-11-update-getlattesdata/
