### ISSUE TITLE
Error in zip file reading

### ISSUE THREAD

**Issue by r-lehtonen** [msperlin/GetLattesData#11]
A função gld_get_lattes_data_from_zip funcionou bem, mas em alguns CVs está aparecendo o erro abaixo e não consegui identificar a causa:
Found 11 published papers
	Found 0 accepted paper(s)
	Found 25 supervisions
	Found 0 published books
	Found 1 book chapters
	Found 55 conference papers Error in `$<-.data.frame`(`*tmp*`, "SJR", value = NA) : 
  replacement has 1 row, data has 0
In addition: Warning message:
In is.na(idx) : is.na() applied to non-(list or vector) of type 'NULL'

**Comment by msperlin** [comment]
Oi,

Me passa o link (oou endereço lattes) do arquivo zip q deu erro para eu checar.

**Comment by r-lehtonen** [comment]
Estava montando um script com os professores do nosso programa de pós e apenas 8 dos 22 deram certo. Os demais apresentaram aquele erro. Segue abaixo alguns que deram errado:
http://lattes.cnpq.br/4051534415496155
http://lattes.cnpq.br/9445516338925875
http://lattes.cnpq.br/6328119050375466

**Comment by msperlin** [comment]
Aqui deu certo:

> out <- gld_read_zip(my.f)

Reading  4051534415496155.zip -  Ana Claudia Bonatto
	Found 11 published papers
	Found 0 accepted paper(s)
	Found 25 supervisions
	Found 0 published books
	Found 1 book chapters
	Found 55 conference papers

Tente instalar a versão do github do pacote, com as atualizações:

`devtools::install_github('msperlin/GetLattesData')`

Rode de novo e me diga como foi.

**Comment by msperlin** [comment]
Achei o problema, era com outra função. Vou checar.

**Comment by msperlin** [comment]
Arrumei o problema:

> out <- gld_get_lattes_data_from_zip(zip.files = my.f)


Reading  4051534415496155.zip -  Ana Claudia Bonatto
	Found 11 published papers
	Found 0 accepted paper(s)
	Found 25 supervisions
	Found 0 published books
	Found 1 book chapters
	Found 55 conference papers
Reading  6328119050375466.zip -  Daniela Fiori Gradia
	Found 13 published papers
	Found 0 accepted paper(s)
	Found 19 supervisions
	Found 0 published books
	Found 0 book chapters
	Found 7 conference papers
Reading  9445516338925875.zip -  Daniela Morais Leme
	Found 21 published papers
	Found 0 accepted paper(s)
	Found 18 supervisions
	Found 0 published books
	Found 2 book chapters
	Found 57 conference papers

Instale a nova versão que agora deve funcionar.

`devtools::install_github('msperlin/GetLattesData')`

**Comment by r-lehtonen** [comment]
Deu certo, instalei a nova versão e carregou todos CVs perfeitamente.
Obrigado pela ajuda. 
Esse pacote é muito útil.
