### ISSUE TITLE
Leitura de Lattes extraído do serviço de Extração da Plataforma Lattes

### ISSUE THREAD

**Issue by Morais14** [msperlin/GetLattesData#12]
Os currículos extraídos do serviço de extração da Plataforma Lattes para instituições conveniadas apresentam estrutura diferente dos currículos baixados via web manualmente.  Um exemplo pode ser visto neste arquivo anexo:
[curriculo.zip](https://github.com/msperlin/GetLattesData/files/3600598/curriculo.zip)

Existe a possibilidade de flexibilizar o GetLttesData para este escopo?

Aproveito para parabenizá-lo pelo pacote!:)

**Comment by msperlin** [comment]
Oi Morais,

A mudança de formato do xml não é simples de fazer. Infeliizmente não tem como acomodar um novo formato no pacote. Todos a árvore do xml teria que ser reconstruída e manualmente encontrar os valores de interesse. 

At,
