### ISSUE TITLE
Problems reading data based on Qualis and from Lattes

### ISSUE THREAD

**Issue by alecamar** [msperlin/GetLattesData#13]
Thanks for your package. It really helps in generating new graduate program proposals, and reports for Capes.

I had two problems when using your package:

1. Apparently, professores that haven’t done Masters, and went straight for phD the data were not readed from the zip file.
Error in names(MESTRADO) <- paste0("MSC-", names(MESTRADO)) : attempt to set an attribute on NULL

2. Problems reading Qualis dataset, when for example, the name of the journal is not exactly as the one in the Qualis table. Had problems a few times with the (PRINT) that is not always in the Lattes, example:

AGROECOLOGY AND SUSTAINABLE FOOD SYSTEMS (PRINT) in Qualis Table
AGROECOLOGY AND SUSTAINABLE FOOD SYSTEMS in Lattes CVs

I will make a pull request.

Thanks once again

**Comment by msperlin** [comment]
Hi alecamar,

This problem with MSC and DOUT was fixed in the last update. I'm pushing the changes to CRAN right now. 

As for qualis, the difference is probably due to change in Qualis. However, all journals are matched by ISSN (and not name).

**Comment by alecamar** [comment]
Dear Marcelo,

Thanks for your prompt reply! Thanks again for your work!

Alexandre



Alexandre Camargo Martensen
www.needs.ufscar.br

Em sáb, 7 de mar de 2020 11:04, Marcelo S. Perlin <notifications@github.com>
escreveu:
