### ISSUE TITLE
Update Qualis and JCR

### ISSUE THREAD

**Issue by bonattod** [msperlin/GetLattesData#17]
Is it possible to update the Qualis and JCR tables for the last version? Or is it possible to update it locally without download the original code and change the respective lines where QUALIS and JCR tables are invocated?

**Comment by msperlin** [comment]
Hi Diego,

The JCR table is proprietary and I can't include it within the code. The current JCR iwll be replaced by SJR, which is free of use.

 But, if you have a JCR table, you can easily merge externally it using the journal ISSN .
