### ISSUE TITLE
Some Lattes Id have less than 10 characters

### ISSUE THREAD

**Issue by cdshikida1** [msperlin/GetLattesData#2]
Hi, thanks for this library. I was testing it and some lattes id I've analysed doesn't have 10 characters. The library doesn't work in this case. Maybe a fix could be a good idea. 

Again, thanks for the library. Great job!

**Comment by msperlin** [comment]
I'm surprised! Can you please send me an example of id with less than 10 chars? You can post it here..

**Comment by msperlin** [comment]
I need it for debugging and check if there is any special treatment for those.

**Comment by cdshikida1** [comment]
ok, let me give you one example:

http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=C784408




Obrigado / Thanks for your time and attention.

Claudio D. Shikida


Esta mensagem pode conter informação confidencial e/ou privilegiada. Se
você não for o destinatário ou a pessoa autorizada a receber esta mensagem,
não poderá usar, copiar ou divulgar as informações nela contidas ou tomar
qualquer ação baseada nessas informações. Se você recebeu esta mensagem por
engano, por favor avise imediatamente o remetente, respondendo o presente
e-mail e apague-o em seguida.
This message may contain confidential and/or privileged information. If you
are not the addressee or authorized to receive this for the addressee, you
must not use, copy, disclose or take any action based on this message or
any information herein. If you have received this message in error, please
advise the sender immediately by reply e-mail and delete this message.

**Comment by cdshikida1** [comment]
Actually, you can find more here:

http://wp.ufpel.edu.br/ppgom/ensino/corpo-docente/

Some of us have lattes id with 8 characters, if I am not wrong.


Obrigado / Thanks for your time and attention.

Claudio D. Shikida


Esta mensagem pode conter informação confidencial e/ou privilegiada. Se
você não for o destinatário ou a pessoa autorizada a receber esta mensagem,
não poderá usar, copiar ou divulgar as informações nela contidas ou tomar
qualquer ação baseada nessas informações. Se você recebeu esta mensagem por
engano, por favor avise imediatamente o remetente, respondendo o presente
e-mail e apague-o em seguida.
This message may contain confidential and/or privileged information. If you
are not the addressee or authorized to receive this for the addressee, you
must not use, copy, disclose or take any action based on this message or
any information herein. If you have received this message in error, please
advise the sender immediately by reply e-mail and delete this message.

**Comment by msperlin** [comment]
Indeed there is a special treatment from Lattes. I tried it here and the xml file does not exist for that id. 

But, there is an correspodingn old ID. For exapmle, 

http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=C784408

is equivalent to:

http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4776653U5

So, find those ids with less than 10 chars and search for their names in lattes. Then you'll find the correct id form. 

From the code side, I need to have a look if there is any way to fix it, but no time right now. I'll look into when I can.

**Comment by cdshikida1** [comment]
ahhhhhhhh, ok! Thank you. For a while, we have to do the "reverse" job.
Thank you so much.


Obrigado / Thanks for your time and attention.

Claudio D. Shikida


Esta mensagem pode conter informação confidencial e/ou privilegiada. Se
você não for o destinatário ou a pessoa autorizada a receber esta mensagem,
não poderá usar, copiar ou divulgar as informações nela contidas ou tomar
qualquer ação baseada nessas informações. Se você recebeu esta mensagem por
engano, por favor avise imediatamente o remetente, respondendo o presente
e-mail e apague-o em seguida.
This message may contain confidential and/or privileged information. If you
are not the addressee or authorized to receive this for the addressee, you
must not use, copy, disclose or take any action based on this message or
any information herein. If you have received this message in error, please
advise the sender immediately by reply e-mail and delete this message.
