### ISSUE TITLE
Orientações

### ISSUE THREAD

**Issue by r-lehtonen** [msperlin/GetLattesData#20]
Nas orientações, poderia acrescentar o tipo de orientação (orientador principal ou coorientador)? Pois como não tem esse campo, não consigo filtrar apenas as orientações, que é um ponto importante quando faço as análises no nosso programa. Obrigado.

**Comment by msperlin** [comment]
Oi Ricardo,

Sim, vou adicionar. Lhe aviso por aqui.

At,

**Comment by msperlin** [comment]
Ricardo,

Adicionei a informação sobre o tipo de supervisão. Basta reinstalar com o código disponível no github (devtools::install_github(...)).

Vou fechar o issue. Caso de algum erro, me avise.
