### ISSUE TITLE
Erro na leitura do curriculum lattes

### ISSUE THREAD

**Issue by elpidiofilho** [msperlin/GetLattesData#5]
Quanto tento reproduzir o exemplo que esta na pagina do github observo que é feito o download de 4 arquivos, correspondendo aos 4 pesquisadores mas o tamanho do arquivo .zip é de apenas 92 bytes e em seguida vem a mensagem de erro: 

XML content does not seem to be XML: 'C:\Users\elpid\AppData\Local\Temp\Rtmp4mUPyN/curriculo.xml'
In addition: Warning message:
In utils::unzip(zip.in, exdir = my.tempdir) :
  error 1 in extracting from zip file

**Comment by msperlin** [comment]
Oi Elpidio,

O código parou de funcionar ano passado devido a mudança no site do lattes. O ponto de acesso não existe mais. Nao tem muito o que fazer.
