### ISSUE TITLE
Multiple ISSN

### ISSUE THREAD

**Issue by HemingNM** [msperlin/GetLattesData#6]
Olá Marcelo,

Estou tendo problemas com revistas que possuem múltiplos ISSNs.
Creio que se fizer duas modificações pode solucionar o problema (veja abaixo). Espero ter ajudado.
Abraço

1. função "gld_get_SJR", remover linhas 82 a 84:
df.sjr$Issn <- paste0(stringr::str_sub(df.sjr$Issn, 1, 4),
                        '-',
stringr::str_sub(df.sjr$Issn, 5, 8))

2. função "gld_get_lattes_data", 
Linhas 84 e 94:
substituir "idx <- match(tpublic.published$ISSN, df.sjr$Issn)" por:
idx <- unlist(sapply(gsub("-", "",  tpublic.published$ISSN), 
                function(i, x){
                  r <- grep(i, x)
                  if(length(r) == 0){
                    r <- NA
                  }
                  return(r)
                  } , df.sjr$Issn, USE.NAMES=F))

Linha 87 e 98:
substituir "idx <- match(tpublic.accepted$ISSN, df.sjr$Issn)" por:
idx <- unlist(sapply(gsub("-", "", tpublic.accepted$ISSN), 
                function(i, x){
                  r <- grep(i, x)
                  if(length(r) == 0){
                    r <- NA
                  }
                  return(r)
                  } , df.sjr$Issn, USE.NAMES=F))

**Comment by HemingNM** [comment]
Não há necessidade de modificar as linhas 82 e 87.

**Comment by msperlin** [comment]
Oi Heming, 

Obrigado. Vou dar uma olhada assim que puder. Vou deixar aberto aqui o issue e assim que resolver aviso por aqui.

Abc.

**Comment by msperlin** [comment]
Tu tens um id que eu possa testar?

**Comment by HemingNM** [comment]
K4781135T5

**Comment by msperlin** [comment]
Ok, arrumado. Mudei algumas coisas no seu código para controlar alguns casos indesejáveis.

Nova versão no github.

Obrigado pela contribuição!

Abraço.

**Comment by HemingNM** [comment]
Maravilha! Funcionando perfeitamente, obrigado.

Abraço
