### ISSUE TITLE
Example of usage is not working

### ISSUE THREAD

**Issue by mnunes** [msperlin/GetLattesData#7]
I tried to use this package after CPNq removed captcha last week, but the package example of usage is not working for me. I run

    library(GetLattesData)
    
    # ids from EA-UFRGS
    my.ids <- c('K4713546D3', 'K4440252H7', 
                'K4783858A0', 'K4723925J2')
    
    # qualis for the field of management
    field.qualis = 'ADMINISTRAÇÃO PÚBLICA E DE EMPRESAS, CIÊNCIAS CONTÁBEIS E TURISMO'
    
    l.out <- gld_get_lattes_data(id.vec = my.ids, field.qualis = field.qualis)

and the output I get is

    Downloading file  /var/folders/gc/8hj8csfj73j4l4w93r1f0_vw0000gn/T//RtmpXTuPoH/K4713546D3_2018-08-16.zip
    Downloading file  /var/folders/gc/8hj8csfj73j4l4w93r1f0_vw0000gn/T//RtmpXTuPoH/K4440252H7_2018-08-16.zip
    Downloading file  /var/folders/gc/8hj8csfj73j4l4w93r1f0_vw0000gn/T//RtmpXTuPoH/K4783858A0_2018-08-16.zip
    Downloading file  /var/folders/gc/8hj8csfj73j4l4w93r1f0_vw0000gn/T//RtmpXTuPoH/K4723925J2_2018-08-16.zip
    Reading  K4713546D3_2018-08-16.zipError: XML content does not seem to be XML: '/var/folders/gc/8hj8csfj73j4l4w93r1f0_vw0000gn/T//RtmpXTuPoH/curriculo.xml'
    In addition: Warning message:
    In utils::unzip(zip.in, exdir = my.tempdir) :
      error 1 in extracting from zip file

For what is worth, this is my `sessionInfo()` output:

    > sessionInfo()
    R version 3.5.1 (2018-07-02)
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    Running under: macOS High Sierra 10.13.6
    
    Matrix products: default
    BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
    LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods  
    [7] base     
    
    other attached packages:
    [1] GetLattesData_1.0
    
    loaded via a namespace (and not attached):
    [1] compiler_3.5.1 magrittr_1.5   tools_3.5.1    curl_3.2      
    [5] stringi_1.2.4  stringr_1.3.1  XML_3.98-1.15

I am using the development version of the package.

**Comment by msperlin** [comment]
Hi Marcus,

Lattes is again using Captcha and, therefore, the package is not working. The captcha as turned off for just one day. 

Not much I can do from my side but monitor it once again..

**Comment by mnunes** [comment]
It seems CNPq hates science. Thank you for your time again.

**Comment by msperlin** [comment]
Sadly true. I don't see why an open API would hurt them.
