### ISSUE TITLE
Erro ao baixar o curriculo

### ISSUE THREAD

**Issue by brunojus** [msperlin/GetLattesData#8]
Pessoal, 

Gostaria que ajudassem a resolver o erro que estou tendo ao tentar realizar do download dos currículos ao passar uma lista com os ids. 

`Erro: XML content does not seem to be XML: '/tmp/Rtmp1TJ66h/curriculo.xml'
Além disso: Warning message:
In utils::unzip(zip.in, exdir = my.tempdir) :
  erro 1 na extração a partir de arquivo zip`

Obrigado

**Comment by msperlin** [comment]
Bruno, o pacote deixou de funcionar. O cnpq novamente implementou o captcha. Foi um dia apenas sem o captcha.
